export const privacy = {
  title: "Privacy Policy",
  descriptions: [
    "The Privacy Policy on Gotloaned.com (hereinafter we, us, our, ours, Website, Site) is the formal document, which determines and explains how the information of the user (hereinafter User, Users, You, Your, Yours) is collected, stored, shared and used on the Website. This document was elaborated to make formal guarantee of the protection and security of the information provided on the Website.",
    "This Privacy Policy determines the implication of the information, both personal and non-personal, used on the Website. If You have already shared Your information on the Website and want to eliminate Your details from any records associated with the Website under our regulation and control, You can contact us directly using the contact details we provide on the Website.",
    "The services provided on the Website can be used only by the legal residents of the United States over 18 years old. The operation of the Website is aligned with federal, state and local laws of the USA. Thus, once You willingly register on the Website by submitting Your information via the online form and accepting this Privacy Policy and the Website Terms and Conditions of Use, You confirm that You understand that the use of the information You submit on the Site is governed by these documents. For this reason, You are encouraged to study these documents carefully prior to submitting Your information on the Website.",
    "If You disagree with or misunderstand the clauses of the Terms and Conditions of Use and Privacy Policy of this Website and/or refuse to accept the provisions of the documents stated above, You should cease using the services of the Website and should not provide Your information and register on the Website via online form or in any other way submit and share Your information on the Website. If You have doubts regarding the use of the Website or its services, You can contact us via the details we provide on the Website. If You willingly refuse to use the Website, You should close this and other pages of this Website.",
  ],
  policies: [
    {
      title: "Personally and Non-Personally Identifiable Information",
      contents: [
        "In order to register on the Website and use its services, You need to provide Your personally identifiable information (PII) via the online form on the Website. The way this information is collected, stored, shared, and used is determined by the provisions of this Privacy Policy. This information is essential to provide You with the service You request by using the Website. If You do not need to use the service of the Website or for some reason decide to cease the use of the Website, You should not submit Your PII information on the Website. PII includes but is not limited to the following information: Your first and last names, address, email address, telephone number, date of birth, employment information, Social Security number, other ID information, banking information.",
        "SS number and banking information are used only to provide You with the searching and matching service and never shared with any third party marketers and other third parties unless the opposite is determined by the law or required according to special orders from the authorized parties (including but not limited national security issues or alike).",
        "Apart from PII, we collect Your non-personally identifiable information (NPII) available upon Your using the Website regardless of submitting any personal information on the Website. NPII includes but is not limited to the user’s behavioral data, such as Internet Protocol (IP) data, browser details, geo position, user’s operating system, the pages of referral and exiting, date and time details, Internet service provider details etc. The NPII we collect from You can be transmitted to the third parties we contract with unless You exploit the means to hide Your NPII or express Your request to stop using Your NPII directly.",
      ],
    },
    {
      title: "The Use of Your PII",
      contents: [
        "We collect, store, share and use Your PII information under the provisions of this Privacy Policy. All the information You provide is protected by our top security means and encryption methods. The information You submit by registering for the services is used to perform search and match with one or more lenders we contract with who can provide You with the loan products You expressed Your interest in. Your submission of the information is considered as an expressed will to be matched with a lender or financial service provider. Additionally, the information we collect can be used to contact You in order to provide with the marketing information on the products You expressed You interest in. Moreover, we can use this information to provide protection from potential malicious activity and fraud in the Internet. We will collect, store, share and use Your information only upon Your expressed consent You give while clicking the respective button or ticking the box of consent, which authorizes us to use Your information as set herein.",
        "Some of Your PII (excluding SS number and other sensitive information such as banking information) can be shared with some third parties we contract with in case technical support is needed. These authorized third parties are liable for keeping Your information secure and in no way can use it for any other purpose but the purposes authorized according to the agreement we make, as well as are in no way authorized to share Your information with other third parties. All the activity performed with Your PII is bounded by the provisions of this Privacy Policy and respective formal documents on this Website, as well as the provisions of applicable international laws and the legislation of the USA. Additionally, PII can be shared for consumer reporting with credit bureaus upon Your prior authorization (consumer reporting authorization). However, this procedure is performed by the lenders in a prerogative way, thus, regulated by the legal documents concerning Your communication with Your lender and other financial providers and has nothing to do with this agreement and the use of this Site and its services.",
        "Your PII can be shared with governmental entities, disclosed completely or partially upon request from any authority or authorized organization if such disclosure is lawful and considered necessary for these reasons:",
        "it is ordered or required to comply with the legal processes;",
        "it is obligatory to protect the property of the owner of the Website or its affiliates and in no way contradicts applicable laws;",
        "it is necessary to prevent crime and/or protect national security;",
        "it is necessary to protect personal or public safety.",
        "In case of merging, acquisition, consolidation or purchase of the owning company and its assets, it is possible that Your PII may be transferred and, thus, disclosed to the receiving party on the course of the stated actions. According to the court’s decision on insolvency proceeding, if it takes place, in case of liquidation of the owning company, the liquidating party or the authorized representatives of the company can transfer, sell, dispose or license Your PII within the provisions stated by this court’s decision. In this case, it is possible that the owners of the PII shared on the Website will be notified of the forthcoming procedures and modifications upfront or the notification will be published openly on the Website. It is possible that acquisition, merging and other stated modifications are associated with a non-US company.",
      ],
    },
    {
      title: "Third Party Marketing",
      contents: [
        "It is possible that Your PII can partially (excluding such sensitive information as SS number and banking and financial data) be shared for the marketing purposes with some of third party marketers, lenders and advertisers, we contract with. In this case, the receiving parties, as third part marketers, may use this information and share it with other third party marketers who may initiate marketing activity towards You in the way of presenting You the products You have expressed Your interest previously while submitting Your information. In case You decide to opt out from receiving such marketing messages and/or offers, You can easily unsubscribe and eliminate Your information from the lists compiled by these third party marketers to send You messages simply by using an unsubscribe option (option button or link) in the respective message. The means for marketing activity include but are not limited to direct mail, short messages, online banner ads, telemarketing calls, emails etc.). Apart from that, Your information can be used to track Your online activity and collect Your online behavioral and searching information. This activity is usually performed to improve the quality of the services presented to You online and adjust marketing activity to Your requirements and needs.",
        "Keep in mind that the way third party marketers use Your information is subject to the provisions of their legal documentation and regulations, including but not limited to the privacy policies and the terms of use of their websites and services. For this reason, since we take no obligations for the manner Your information can be used by these parties, we encourage You to acknowledge how Your information is to be used according to the provisions of the legal documentation of these third party marketers. If You wish to eliminate Your information from any of the lists or databases of these third party marketers, You should contact them directly.",
        "By continuous use of the Website and attempt to use the services presented on the Website, You expressly agree that You have read and understand the provisions of the legal documents, which control the use of Your information on the Website, and the terms of collecting, storing, sharing and using of You PII and the way Your shared PII can be used by third party lenders and third party marketers.",
        "In order to discontinue contacting with us and receiving more information from Us, You need to close this and all other Website pages. If You have already shared Your personal information with us and want to opt out from further communication and remove Your information from our lists and database, You can contact us directly with respective request using this email address help@gotloaned.com or other contact information indicated on this Website. Your request will be processed and the information removed from our database. As soon as Your information is removed from out database, You can be sure it will not be shared with any third party, used for any secondary purposes, or used for marketing activities. Still, since the information has already been shared with third party marketers, we cannot take any responsibility for the communication sent to You by these third parties. You should contact third party marketers directly to remove Your information from their databases.",
      ],
    },
    {
      title: "Credit Implication of the Use of PII",
      contents: [
        "The information shared with our third party lenders can be used to verify Your identity (via SS number and/or driving license number, for example) and Your information against national databases. Additionally, the lenders we contract with may need to perform credit verification and use Your PII to request a credit report from one or more credit organizations, including but not limited to the major credit bureaus, to determine Your credibility and assess the risks associated with providing credit products to You. Credit report request may lower Your credit score. If You continue using the Website and submit Your information via the online form on the Website, You give Your express consent to have Your information verified and Your credibility checked according to the provisions of these third party lenders’ legal documents used to govern and regulate their practices and communication with You.",
      ],
    },
    {
      title: "Email and Telemarketing",
      contents: [
        "By agreeing to the Terms and Conditions of Use and this Privacy Policy, You confirm that we and third party lenders and marketers with whom Your information is shared according to the provisions of this Privacy Policy can use Your PII for advertising purposes, including but not limited to email and telemarketing advertising.",
        "Your PII can be used for direct and indirect communication, including but not limited to telemarketing calls, assistance calls and credit product and service offers via the telephone number You have provided in the online form. Either we or third party lenders and marketers can use this number even though it is listed in any corporate, state, or federal Do-Not-Contact registry, suppression lists or the like. Since Your submitting of the information via online form is determined as an attempt to make a purchase or receive a service, the processing and application of Your request is performed according to the provisions of Amended Telemarketing Sales Rule, 16 CFR §310 et seq. (the 'ATSR'). According to ATSR, even if Your telephone number is listed in FTC Do-Not-Call List, we are authorized to contact You upon Your given consent using telemarketing. Since Your inquiry to third party marketers and request for the service on the Website are also considered as a an attempt to make a purchase, according to ATSR these third party marketers are also authorized to contact You using telemarketing.",
        "By giving Your consent to use the Website and provide Your information to use our services, You confirm that You are at least 18 years old and legally authorized to own and use a mobile device. You also confirm that You realize and understand the liabilities and possible charges associated with Your participation in telemarketing campaigns. Your service provider may also collect Your information. These procedures and interaction with Your service provider are regulated by the policies and terms stated by these organizations and have nothing to do with this Privacy Policy and other regulating documents on this Website.",
      ],
    },
    {
      title: "The Means to Collect Non-Personally Identifiable Information",
      contents: [
        "If You opt to use the Website or the Websites of third party lenders and marketers, You may encounter the use of cookies, web beacons, pixel tags, browser analysis tools and web server logs. These are small files or parts of code, used to monitor and record the features of Your online activity, such as Your geographical position, IP address, language preferences, click history, browsing history, online behavior, You operating system and browser specifications set. All this data is considered as Your non-personally identifiable information (NPII) and collected and stored to provide the customization of Your online activity.",
      ],
    },
    {
      title: "Inquiries and Complaints",
      contents: [
        "The users of the Website are within their rights to modify, amend and withdraw their PII collected on the Website. In case it is necessary, the user who decides to make changes to their own information should contact us via email help@gotloaned.com or other contact details stated on the Website and provide inquiry regarding the modifications to be made. Similarly, if any user of the Website has any complaint regarding the operation on the Website and/or any of its service, this user should use the stated contact details and provide the details of complaint. We will review all requests and complaints in the shortest time possible and reply as soon as we can.",
        "Nevertheless, we encourage all the users of the Website to revise the Privacy Policy information and follow the dates of modifications to keep up to date and react in case it is deemed reasonable.",
      ],
    },
    {
      title: "Inquiries and Complaints",
      contents: [
        "The users of the Website are within their rights to modify, amend and withdraw their PII collected on the Website. In case it is necessary, the user who decides to make changes to their own information should contact us via email help@gotloaned.com or other contact details stated on the Website and provide inquiry regarding the modifications to be made. Similarly, if any user of the Website has any complaint regarding the operation on the Website and/or any of its service, this user should use the stated contact details and provide the details of complaint. We will review all requests and complaints in the shortest time possible and reply as soon as we can.",
      ],
    },
  ],
};
